templates:
  judge:
  - default
  - simple
  sft:
  - default
  - structured
  - fewshot
validation:
  auto_repair: true
  max_answer_chars: 120
  max_citation_index: n_chunks - 1
  no_citation_max_confidence: 0.3
  refusal_max_confidence: 0.1
  strict_mode: false
